name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compilar-desplegar.yml'
      - 'GithubActionsDemoApp/**'
      - 'pruebas/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v5.3.0
        with:
          dotnet-version: 8.0.x

      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar las pruebas
        run: dotnet test --no-build











        
